import type { Course, UserRole } from "../../../types";
import { mockApi } from "../../../services/mockApi";

const courses: Course[] = [
  {
    id: "c-101",
    title: "Design Systems for Product Teams",
    category: "Design",
    level: "Advanced",
    instructor: "Sarah Chen",
    progress: 78,
    lessons: 24,
    duration: "10h",
    status: "Published",
    students: 2340,
    rating: 4.9,
    thumbnail: "🎯",
    description:
      "Build reusable systems, patterns, and component libraries with confidence.",
    nextLesson: "Module 5: Compound Components",
    isEnrolled: true,
    price: "90,000",
  },
  {
    id: "c-102",
    title: "Machine Learning Fundamentals",
    category: "Data Science",
    level: "Intermediate",
    instructor: "Dr. Alex Kim",
    progress: 42,
    lessons: 18,
    duration: "16h",
    status: "Published",
    students: 5120,
    rating: 4.8,
    thumbnail: "🤖",
    description:
      "Learn core ML workflows, models, and evaluation techniques from scratch.",
    nextLesson: "Module 3: Neural Networks",
    isEnrolled: true,
    price: "90,000",
  },
  {
    id: "c-103",
    title: "UI/UX Design Masterclass",
    category: "Design",
    level: "Beginner",
    instructor: "Maya Patel",
    progress: 85,
    lessons: 21,
    duration: "12h",
    status: "Published",
    students: 3200,
    rating: 4.7,
    thumbnail: "🎨",
    description:
      "Create polished interfaces with practical UX flows and visual hierarchy.",
    nextLesson: "Module 8: Design Systems",
    isEnrolled: true,
    price: "90,000",
  },
  {
    id: "c-104",
    title: "TypeScript Deep Dive",
    category: "Development",
    level: "Intermediate",
    instructor: "John Smith",
    progress: 0,
    lessons: 14,
    duration: "8h",
    status: "Published",
    students: 1890,
    rating: 4.8,
    thumbnail: "📘",
    description:
      "Master typing patterns, generics, and scalable frontend architecture.",
    isRecommended: true,
    price: "99,000",
  },
  {
    id: "c-105",
    title: "Cloud Architecture with AWS",
    category: "Cloud",
    level: "Advanced",
    instructor: "Tom Wilson",
    progress: 0,
    lessons: 20,
    duration: "14h",
    status: "Published",
    students: 1560,
    rating: 4.6,
    thumbnail: "☁️",
    description:
      "Design resilient cloud systems with networking, compute, and observability.",
    isRecommended: true,
    price: "90,000",
  },
  {
    id: "c-106",
    title: "Python for Data Analysis",
    category: "Data Science",
    level: "Beginner",
    instructor: "Lisa Wang",
    progress: 0,
    lessons: 17,
    duration: "10h",
    status: "Published",
    students: 4200,
    rating: 4.9,
    thumbnail: "🐍",
    description:
      "Analyze real datasets using Python, notebooks, and data-cleaning workflows.",
    isRecommended: true,
    price: "90,000",
  },
  {
    id: "c-107",
    title: "Node.js Microservices",
    category: "Development",
    level: "Advanced",
    instructor: "James Lee",
    progress: 0,
    lessons: 19,
    duration: "11h",
    status: "Review",
    students: 980,
    rating: 4.5,
    thumbnail: "🔧",
    description:
      "Ship service-oriented backend systems with queues, APIs, and monitoring.",
    price: "90,000",
  },
  {
    id: "c-108",
    title: "Digital Marketing Strategy",
    category: "Marketing",
    level: "Beginner",
    instructor: "Emma Davis",
    progress: 0,
    lessons: 13,
    duration: "7h",
    status: "Published",
    students: 3100,
    rating: 4.7,
    thumbnail: "📣",
    description:
      "Plan channels, campaigns, and analytics with a clear growth framework.",
    price: "90,000",
  },
  {
    id: "c-109",
    title: "Leadership Communication",
    category: "Business",
    level: "Intermediate",
    instructor: "Amelia Brooks",
    progress: 0,
    lessons: 12,
    duration: "6h",
    status: "Draft",
    students: 64,
    rating: 4.7,
    thumbnail: "🗣️",
    description:
      "Lead difficult conversations with clarity, trust, and executive presence.",
    price: "90,000",
  },
];

export const courseService = {
  async getCourses(role: UserRole) {
    if (role === "admin") {
      return mockApi(courses);
    }

    return mockApi(courses.filter((course) => course.status !== "Draft"));
  },
};
